name: Publish Design System Package in NPM

on:
  release:
    types: [created]

permissions:
  contents: read
  packages: write

env:
  NODE_VERSION: "22"
  NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


jobs:
  publish-gpr:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out repository
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://npm.pkg.github.com"
          scope: "@peter-p-prat"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build package
        run: yarn build

      - name: Configure yarn
        run: |
          yarn config set npmRegistryServer "https://npm.pkg.github.com"
          yarn config set npmScopes.peter-p-prat.npmRegistryServer "https://npm.pkg.github.com"
          yarn config set npmScopes.peter-p-prat.npmAlwaysAuth true
          yarn config set npmScopes.peter-p-prat.npmAuthToken $NPM_AUTH_TOKEN

      - name: Publish package
        run: yarn npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
